language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install: 
  - chmod +x .github/scripts/deploy/telegram.sh
script:
  - bash ./gradlew assembleDebug check
  - bash ./gradlew app:assembleRelease check

deploy:
  - provider: script
    skip_cleanup: true
    script: .github/scripts/deploy/telegram.sh
    on:
      branch: master
